include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    parameter_assignments: false
    prefer_relative_imports: true
    unnecessary_await_in_return: false
    prefer_final_locals: false
    prefer_final_in_for_each: false
    unnecessary_final: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

plugins:
  _internal_plugin:
    path: _internal_plugin/
