include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
